version: '2'

services:
  mongodb:
    image: docker.io/bitnami/mongodb:5.0
    ports:
      - "27017:27017"
    volumes:
      - 'mongodb_data:/bitnami/mongodb'
    # env_file:
    #   - .env
# networks:
#   default:
#     name: service_network
volumes:
  mongodb_data:
    driver: local
