version: "3"

services:
  weather:
    image: weather
    ports:
      - "2555:2555"
    env_file: w.env
    networks:
      - services

  mongodb:
    image: docker.io/bitnami/mongodb:5.0
    ports:
      - "27017:27017"
    volumes:
      - 'mongodb_data:/bitnami/mongodb'
    networks:
      - database

  rabbitmq:
    image: docker.io/bitnami/rabbitmq:3.9
    ports:
      - '4369:4369'
      - '5551:5551'
      - '5552:5552'
      - '5672:5672'
      - '25672:25672'
      - '15672:15672'
    environment:
      - RABBITMQ_SECURE_PASSWORD=yes
    volumes:
      - 'rabbitmq_data:/bitnami/rabbitmq/mnesia'
    networks:
      - rabbit
  
  authenticator:
    image: authenticator
    ports:
      - "5025:5025"
    env_file: auth.env
    networks:
      - database
      - services
    depends_on:
      - mongodb

  networks:
    image: network
    env_file:
      - net.env
    ports:
    - "5050:5050"
    networks:
      - database
      - services
      - rabbit
    depends_on:
      - mongodb
      - rabbitmq
      - authenticator

  simulator:
    image: simulator
    ports:
      - "5001:5001"
    env_file: auth.env
    networks:
      - database
      - rabbit
      - services
    depends_on:
      - mongodb
      - weather
      - networks
      - rabbitmq
      - authenticator
  image_service:
    image: rms
    ports:
      - "2525:2525"
    env_file:
      - rms.env
    networks:
      - services
#    volumes:
#      - rms_data
    depends_on:
      - authenticator

volumes:
  rabbitmq_data:
    driver: local

  mongodb_data:
    driver: local

#  rms_data:
#    driver: local

networks:
  services:
    driver: bridge
  database:
    driver: bridge
  rabbit:
    driver: bridge
    
